### ISSUE TITLE
Initial app startup when no settings are saved: how to initiate the NSUserDefaults?

### ISSUE THREAD

**Issue by wkoszek** [futuretap/InAppSettingsKit#360] opened 2016-09-09 06:48 UTC
Hi,

I have an app and I've integrated InAppSettings. My understanding is that once InAppSettings manages the Settings values, I'm expected to use NSUserDefaults API to get the values that IASK manages. Now: I have many toggle switches with `DefaultValue` keys set. However I see no way to write them to NSUserDefaults at the very first app startup.

Example:
- new user installs an app
- my app code would be checking NSUserDefaults all over, but with the very first app startup the settings dictionary of NSUserDefaults is empty.

How do people currently solve this problem? I guess this looks similar:

https://github.com/futuretap/InAppSettingsKit/issues/244

But maybe I'm thinking wrong about this. Just wondering what you guys already do for the initial app startup.

**Comment by gereons** [comment] 2016-09-09 07:17
Use `NSUserDefaults.standardUserDefaults().registerDefaults()`.

**Comment by wkoszek** [comment] 2016-09-09 22:42
@gereons In `Root.plist` I've already defined the default values for my keys. I think you're suggesting that I duplicate those in a separate dictionary and use `registerDefaults` ?

Was thinking about doing this automatically via IASK, since it already has the knowledge of what the default values should be.

**Comment by gereons** [comment] 2016-09-10 10:34
I rely on `registerDefaults()` exclusively, mainly because not all NSUserDefault entries are user-settable, so there's no plist default value entry for them, and I like to have all my settings defaults in one easy-to-find place instead of scattered around in multiple plist files.

**Comment by futuretap** [comment] 2016-12-01 16:39
Closing this since this is either answered by using `registerDefaults` or a dupe of #244.

**Closed by futuretap** 2016-12-01 16:39 UTC
