### ISSUE TITLE
UITableViewCell background color is clear on iOS 14

### ISSUE THREAD

**Issue by Will949** [futuretap/InAppSettingsKit#437] opened 2020-08-24 05:57 UTC
Hi :
I encountered a problem which was the `UITableViewCell` color was `clear` on iOS 14 when the setting page has first appeared.
However, cell color will be recovered after I push a view controller from the setting page and go back.

Has anyone suffered the same problem as me?

SDK Version: 3.1.3
Xcode Version : 12.0 beta-5

<img width="584" alt="Screen Shot 2020-08-24 at 3 42 42 PM" src="https://user-images.githubusercontent.com/69958769/91017239-87ce2f00-e620-11ea-89ee-3b9a5e2371ce.png">

Thanks.

**Comment by futuretap** [comment] 2020-09-29 22:46
I haven't seen this so far. Does this still happen with the latest iOS 14.0.1? If yes, can you share a sample app?

**Comment by futuretap** [comment] 2021-01-19 10:53
Closing this for now since I can't reproduce.

**Closed by futuretap** 2021-01-19 10:53 UTC
